function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(3)=0;
    ys_(2)=(params(1)*params(2))^(1/(1-params(1)));
    ys_(1)=ys_(2)^params(1)-ys_(2);
    % Auxiliary equations
end
